### PR TITLE
Adds Comet Lake laptop device ID.

### PR DESCRIPTION
**Pull request by fewtarius**
This works perfectly on my Comet Lake laptop.

### CODE REVIEW

**Comment by Andrey1970AppleLife** [comment]
It doesn't make sense.
AppleIntelCFLGraphicsFramebuffer.kext doesn't contain device-id 0x9B41
You shall use a fake device-id as CFL.

**Comment by fewtarius** [comment]
Sorry to bring this one back out of the blue but I'm just finishing up this build.  I'm already using a fake device ID of 9B3E0000 which does not work with the unpatched PNLF, nor does it work with that plus the cfl brightness WEG properties patch.  The only way brightness works using the non-modified pnlf ssdt is to use device id C0870000 (UHD 617) but using that device id along with igfxfw=2 causes a sleep panic.  Using 9B3E0000 + igfxfw=2 and this pnlf adjustment, everything works perfectly.  Should I file a bug report instead?

**Comment by Andrey1970AppleLife** [comment]
Use SSDT-PNLFCFL.aml
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

**Comment by andrewwyatt** [comment]
> Use SSDT-PNLFCFL.aml
> https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md

Thanks, this fixed the problem for me.  I thought the device property did the same thing.

**Comment by fewtarius** [comment]
Thanks, this fixed it.  I mistakenly thought that the device property patch did the same thing.

**Pull request closed without merging**
