### PR TITLE
backlight patch for icl

### PR DESCRIPTION
**Pull request by idalin**
Copied codes from bkl patch for coffee and kaby and applied to icl

### CODE REVIEW

**Comment by Lorys89** [comment]
I compiled the kext and tried it in my ice lake notebook, now it works great and immediately the backlight, thanks 😘

**Comment by Lorys89** [comment]
you know how to solve, at the end of loading apple you see desk for 2 seconds then disappears for 5 seconds and eventually reappears. if you try to fix🙈💪

**Comment by m0d16l14n1** [comment]
@idalin @Lorys89 like that? https://github.com/acidanthera/bugtracker/issues/1329

**Comment by Lorys89** [comment]
have you been able to patch HDMI output? And TYPE C to HDMI? of course on windows they both work well.

**Comment by Lorys89** [comment]
@0xFireWolf @vit9696

**Comment by m0d16l14n1** [comment]
@Lorys89 read here about HDMI - https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/issues/3#issuecomment-711080776

**Comment by vit9696** [comment]
I do not like that the code is copy-pasted for a third time.

**Comment by idalin** [comment]
> I do not like that the code is copy-pasted for a third time.

I don't like that either actually...
I just can't find a better way

**Comment by Lorys89** [comment]
> Non mi piace che il codice venga copiato per la terza volta.

but I compiled with its modification and solved, maybe there will be other ways to solve.

**Comment by Andrey1970AppleLife** [comment]
CC @hieplpvip

**Comment by thefiredragon** [comment]
Could someone provide this kext with the patch above? 

Von meinem iPhone gesendet

**Comment by Lorys89** [comment]
> Qualcuno potrebbe fornire a questo kext la patch sopra? Von meinem iPhone gesendet
> [...](#)
> Am 27.11.2020 um 16:09 schrieb Andrey1970AppleLife ***@***.***>: ﻿ CC @hieplpvip — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

[WhateverGreen.kext.zip](https://github.com/acidanthera/WhateverGreen/files/5609186/WhateverGreen.kext.zip)

**Comment by m0d16l14n1** [comment]
> test this compiled kext + this ssdt pnlf and use this bootargs igfxcflbklt=1

@idalin @Lorys89 @vit9696 

In my case i have no difference between "default" WEG/"default" ssdt and no bootarg and your compiled kext/ssdt/boot-arg. I have no problems with brightness at all. I still have only [that problem](https://github.com/acidanthera/bugtracker/issues/1329) with default kext or new compiled version/changes.

**Comment by thefiredragon** [comment]
> > Qualcuno potrebbe fornire a questo kext la patch sopra? Von meinem iPhone gesendet
> > [...](#)
> > Am 27.11.2020 um 16:09 schrieb Andrey1970AppleLife _**@**_.***>: ﻿ CC @hieplpvip — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> test this compiled kext + this ssdt pnlf and use this bootargs igfxcflbklt=1
> 
> [WhateverGreen.kext.zip](https://github.com/acidanthera/WhateverGreen/files/5609186/WhateverGreen.kext.zip)
> [SSDT-PNLF.aml.zip](https://github.com/acidanthera/WhateverGreen/files/5609491/SSDT-PNLF.aml.zip)

It's not working for me, issue for me, max brightness is too low. 
With this kext and patch after initial screen device force reboots.

**Comment by m0d16l14n1** [comment]
> It's not working for me, issue for me, max brightness is too low.
> With this kext and patch after initial screen device force reboots.

What's your graphics card? Ice Lake?

**Comment by thefiredragon** [comment]
yes, had open a ticket and also tried to use inject custom Pwm max.
But I'll sell this notebook. It's an Lenovo yoga slim 7 with i7 1065G7.
Brigthness slider is working, but the display is to dark at maximum level to work with it.

**Comment by Lorys89** [comment]
> > > Qualcuno potrebbe fornire a questo kext la patch sopra? Von meinem iPhone gesendet 
> > > [...](#) 
> > > Am 27.11.2020 um 16:09 schrieb Andrey1970AppleLife _**@**_ . ***>: CC @hieplpvip - Hai ricevuto questo messaggio perché sei iscritto a questo thread. Rispondi direttamente a questa email, visualizzala su GitHub o annulla l'iscrizione.
> > 
> > 
> > prova questo kext compilato + questo ssdt pnlf e usa questo bootargs igfxcflbklt = 1
> > [WhateverGreen.kext.zip ](https://github.com/acidanthera/WhateverGreen/files/5609186/WhateverGreen.kext.zip)
> > [SSDT-PNLF.aml.zip](https://github.com/acidanthera/WhateverGreen/files/5609491/SSDT-PNLF.aml.zip)
> 
> Non funziona per me, problema per me, la luminosità massima è troppo bassa.
> Con questo kext e patch dopo il riavvio forzato del dispositivo della schermata iniziale.

uses only kext and bootarg and ssdt pnlf cfl, and disables kext apple blacklight smoter

**Comment by CobanRamo** [comment]
So with my Lenovo S340-15IIL IceLake with 1065G7 IGPU the problem is not completely solved either.
Here are my symptoms;
After sleep or after LID activation, it is simply much brighter.
After sleep or LID activation, it is just as bright as under Windows.

Bildschirmfoto 2020-11-28 um 13 26 35
Bildschirmfoto 2020-11-28 um 13 27 54
Bildschirmfoto 2020-11-28 um 13 43 46
Bildschirmfoto 2020-11-28 um 13 46 19

https://drive.google.com/file/d/1Fb5ao8lS0YSgj7bQIOCd5R-ABKq3gPvV/view?usp=sharing

**Comment by m0d16l14n1** [comment]
> here is the video

open access to the video please. 

image

**Comment by Lorys89** [comment]
> So with my Lenovo S340-15IIL IceLake with 1065G7 IGPU the problem is not completely solved either.
> Here are my symptoms;
> After sleep or after LID activation, it is simply much brighter.
> After sleep or LID activation, it is just as bright as under Windows.
> 
> Bildschirmfoto 2020-11-28 um 13 26 35
> Bildschirmfoto 2020-11-28 um 13 27 54
> Bildschirmfoto 2020-11-28 um 13 43 46
> Bildschirmfoto 2020-11-28 um 13 46 19
> 
> [here is the video](https://akustik.sircalik.com/IceLake_Backlight_problem.mp4)
> sorry, link corrected ...

try more igpu patch, later I'll give you my patch

**Comment by CobanRamo** [comment]
@Lorys89 thanks for the support.
maybe a bit oftopic but the patch doesn't help me.

I can adjust the graphic for me.
Bildschirmfoto 2020-11-28 um 17 25 18
Bildschirmfoto 2020-11-28 um 17 24 36

You use the original ID, which causes other problems for me.
I tried this one too, but it doesn't change the backlight level problem either.
Bildschirmfoto 2020-11-28 um 17 36 20
Bildschirmfoto 2020-11-28 um 17 31 32

have now switched to dark mode so that you can see the backlight level before and after Sleep or Lid.
after Sleep or Lid it is simply lighter than before.

[see video ...](http://akustik.sircalik.com/IceLakeBrighness.mp4)

**Comment by thefiredragon** [comment]
> @Lorys89 thanks for the support.
> maybe a bit oftopic but the patch doesn't help me.
> 
> I can adjust the graphic for me.
> Bildschirmfoto 2020-11-28 um 17 25 18
> Bildschirmfoto 2020-11-28 um 17 24 36
> 
> You use the original ID, which causes other problems for me.
> I tried this one too, but it doesn't change the backlight level problem either.
> Bildschirmfoto 2020-11-28 um 17 36 20
> 
> Bildschirmfoto 2020-11-28 um 17 31 32
> 
> have now switched to dark mode so that you can see the backlight level before and after Sleep or Lid.
> after Sleep or Lid it is simply lighter than before.
> 
> [see video ...](http://akustik.sircalik.com/IceLakeBrighness.mp4)

How you got adavnced Features bios settings? Did you flashed hacked bios over eprom?

**Comment by CobanRamo** [comment]
@thefiredragon 
No, with my Lenovo S340-15IIL IceLake I can activate DebugBios and make detailed settings.

**Comment by thefiredragon** [comment]
How you enabled DebugBios? Was this a setting ? (sorry for this off topic)

**Comment by m0d16l14n1** [comment]
> @thefiredragon 
> 
> No, with my Lenovo S340-15IIL IceLake I can activate DebugBios and make detailed settings.

i got that settings too. here they are 
image

**Comment by frozenzero123** [comment]
> > @thefiredragon
> > No, with my Lenovo S340-15IIL IceLake I can activate DebugBios and make detailed settings.
> 
> i got that settings too. here they are. As i see, we have some differences there, but i am not sure if it's gonna be okay to change something there except DVMT size, heh. I got that settings unlocked via modification of AMI, also guys from win-raid helped me to unlock Overclocking menu.
> 
> image

How did you unlock the hidden adviced settings of bios？

**Comment by frozenzero123** [comment]
> @Lorys89 thanks for the support.
> maybe a bit oftopic but the patch doesn't help me.
> 
> I can adjust the graphic for me.
> Bildschirmfoto 2020-11-28 um 17 25 18
> Bildschirmfoto 2020-11-28 um 17 24 36
> 
> You use the original ID, which causes other problems for me.
> I tried this one too, but it doesn't change the backlight level problem either.
> Bildschirmfoto 2020-11-28 um 17 36 20
> 
> Bildschirmfoto 2020-11-28 um 17 31 32
> 
> have now switched to dark mode so that you can see the backlight level before and after Sleep or Lid.
> after Sleep or Lid it is simply lighter than before.
> 
> [see video ...](http://akustik.sircalik.com/IceLakeBrighness.mp4)

same question！How did you unlock the hidden adviced settings of bios？

**Comment by m0d16l14n1** [comment]
> How did you unlock the hidden adviced settings of bios？

A little bit offtopic, but there is lots of guides how to properly unlock AMI based BIOS (i did it with the guide from Russian forum 4pda + guys from win-raid helped me to unlock Overclock menu). In your case - Lenovo usually using InsydeH2O bioses and there is no "guides" to that unlock. But some guys from win-raid can perform an unlock for you if you have SPI flasher (to get full dump and than flash modified). [Here](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/tree/master/Tools/BIOS) you can see instruction for my laptop with AMI bios. Also, sometimes vendors keep some key combos to get into debug (full) bios, but they are unknown for many laptops.

**Comment by frozenzero123** [comment]
> > How did you unlock the hidden adviced settings of bios？
> 
> A little bit offtopic, but there are lots of guides how to properly unlock AMI based BIOS (i did it with the guide from Russian forum 4pda + guys from win-raid helped me to unlock Overclock menu). In your case - Lenovo usually using InsydeH2O bioses and there is no "guides" to that unlock. But some guys from win-raid can perform an unlock for you if you have SPI flasher (to get full dump and than flash modified). [Here](https://github.com/Ardentwheel/OpenCore-Hasee-X57S1/tree/master/Tools/BIOS) you can see instruction for my laptop with AMI bios. Also, sometimes vendors keep some key combos to get into debug (full) bios, but they are unknown for many laptops.
> 
> And here is example of my [old Lenovo laptop InsydeH2O bios unlocked](https://github.com/m0d16l14n1/ideapad330-15arr-hackintosh/blob/master/BIOS-UNLOCK.md) (guys from win-raid helped me out with that too)

Thank you! But these methods are too inconvenient for me! I want to find a way for the smart manufacturer to stay! Lenovo's equipment and "hasee" are different

**Comment by frozenzero123** [comment]
> @thefiredragon
> No, with my Lenovo S340-15IIL IceLake I can activate DebugBios and make detailed settings.

How did you unlock the hidden adviced settings of bios？

**Comment by CobanRamo** [comment]
It becomes too much offtopic, if you would allow private messages, I could have delivered it privately.
With Lenovo it is different from series to series.
I can offer you a German manual that I created myself.

I think that we should delete these offtopics afterwards so that we can return to the topic.

[Lenovo Debug Bios Mudus.pdf](https://github.com/acidanthera/WhateverGreen/files/5611810/Lenovo.Debug.Bios.Mudus.pdf)

**Comment by vit9696** [comment]
Implemented in master.

**Pull request closed without merging**
